# Generated by Django 4.1.2 on 2023-02-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagetitle", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagetitle", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(blank=True, max_length=100, null=True)),
                ("timing", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignlocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "lockernumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("keynumber", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "instruction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nominee", models.CharField(blank=True, max_length=100, null=True)),
                ("relnominee", models.CharField(blank=True, max_length=100, null=True)),
                ("valuable", models.CharField(blank=True, max_length=100, null=True)),
                ("idproof", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
                ("image2", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "status",
                    models.CharField(
                        blank=True, default="Inactive", max_length=200, null=True
                    ),
                ),
                ("creationdate", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.lockertype",
                    ),
                ),
            ],
        ),
    ]
