# Generated by Django 4.1.2 on 2023-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_trackinghistory_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackinghistory",
            name="limit",
        ),
        migrations.AddField(
            model_name="application",
            name="limit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
